config/routes.rb
Taxwhere::Application.routes.draw do
  resources :filing_categories
  resources :tax_rates
  resources :spending_rates
  resources :spending_categories
  
  resource :account, :controller => "users"
  resources :users
  resource :user_session
  resources :password_resets, :only => [ :new, :create, :edit, :update ]
  resources :user_verification, :only => :show
  
  
  
  match'/tax_payers', :controller => 'welcome', :action => 'spending'
  match 'credits' => 'welcome#credits'
  match 'sources' => 'welcome#sources'
  match 'spending' => 'welcome#spending'

  root :to => "welcome#index"

end

app/models/spending_category.rb
class SpendingCategory < ActiveRecord::Base
  validates_presence_of :name
  validates_uniqueness_of :name
  
  has_many :spending_rates
end

app/controllers/spending_categories_controller.rb
class SpendingCategoriesController < ApplicationController
  before_filter :require_user
  
  # GET /spending_categories
  # GET /spending_categories.xml
  def index
    @spending_categories = SpendingCategory.find(:all, :joins => :spending_rates,
                                                  :conditions => ["spending_rates.year = ?", APP_CONFIG[:tax_year]],
                                                  :select => "spending_categories.id, spending_categories.name, spending_categories.description, SUM(spending_rates.amount) AS amount_sum",
                                                  :group => "spending_categories.id, spending_categories.name, spending_categories.description")

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @spending_categories }
    end
  end

  # GET /spending_categories/1
  # GET /spending_categories/1.xml
  def show
    @spending_category = SpendingCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @spending_category }
    end
  end

  # GET /spending_categories/new
  # GET /spending_categories/new.xml
  def new
    @spending_category = SpendingCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @spending_category }
    end
  end

  # GET /spending_categories/1/edit
  def edit
    @spending_category = SpendingCategory.find(params[:id])
  end

  # POST /spending_categories
  # POST /spending_categories.xml
  def create
    @spending_category = SpendingCategory.new(params[:spending_category])

    respond_to do |format|
      if @spending_category.save
        format.html { redirect_to(@spending_category, :notice => 'Spending category was successfully created.') }
        format.xml  { render :xml => @spending_category, :status => :created, :location => @spending_category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @spending_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /spending_categories/1
  # PUT /spending_categories/1.xml
  def update
    @spending_category = SpendingCategory.find(params[:id])

    respond_to do |format|
      if @spending_category.update_attributes(params[:spending_category])
        format.html { redirect_to(@spending_category, :notice => 'Spending category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @spending_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /spending_categories/1
  # DELETE /spending_categories/1.xml
  def destroy
    @spending_category = SpendingCategory.find(params[:id])
    @spending_category.destroy

    respond_to do |format|
      format.html { redirect_to(spending_categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/spending_categories_helper.rb
module SpendingCategoriesHelper
end

app/views/spending_categories/_form.html.erb
<%= form_for(@spending_category) do |f| %>
  <% if @spending_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spending_category.errors.count, "error") %> prohibited this spending_category from being saved:</h2>

      <ul>
      <% @spending_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spending_categories/edit.html.erb
<h1>Edit Spending Categories</h1>

<%= render 'form' %>

<%= link_to 'Show', @spending_category %> |
<%= link_to 'Back', spending_categories_path %>

app/views/spending_categories/index.html.erb
<h1>Listing Spending Categories</h1>

<table>
  <tr>
    <th>Name</th>
	<th>Total Amount (millions USD)</th>
    <th>Description</th>
    <th></th>
    <th></th>
  </tr>

<% total = 0 %>
<% @spending_categories.each do |spending_category| %>
  <tr>
    <td><%= link_to spending_category.name, spending_category %></td>
	<td><%= spending_category.amount_sum %></td>
    <td><%= truncate(spending_category.description, :length => 100) %></td>
    <td><%= link_to 'Edit', edit_spending_category_path(spending_category) %></td>
    <td><%= link_to 'Destroy', spending_category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% total = total + spending_category.amount_sum %>
<% end %>
	<tr><td>Total</td><td><%= total %></td><td></td><td></td><td></td></tr>
</table>

<br />

<%= link_to 'New Spending category', new_spending_category_path %>

app/views/spending_categories/new.html.erb
<h1>Create New Spending Category</h1>

<%= render 'form' %>

<%= link_to 'Back', spending_categories_path %>

app/views/spending_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @spending_category.name %>
</p>

<p>
  <b>Description:</b>
  <%= @spending_category.description %>
</p>

<p>
  <b>Has <%= @spending_category.spending_rates.count%> spending rates</b><br />
  <% for spending_rate in @spending_category.spending_rates%>
	<%= spending_rate.name%> (<%= spending_rate.amount%>%)<br />
  <% end %>
</p>

<%= link_to 'Edit', edit_spending_category_path(@spending_category) %> |
<%= link_to 'Back', spending_categories_path %>