config/routes.rb
Taxwhere::Application.routes.draw do
  resources :filing_categories
  resources :tax_rates
  resources :spending_rates
  resources :spending_categories
  
  resource :account, :controller => "users"
  resources :users
  resource :user_session
  resources :password_resets, :only => [ :new, :create, :edit, :update ]
  resources :user_verification, :only => :show
  
  
  
  match'/tax_payers', :controller => 'welcome', :action => 'spending'
  match 'credits' => 'welcome#credits'
  match 'sources' => 'welcome#sources'
  match 'spending' => 'welcome#spending'

  root :to => "welcome#index"

end

app/models/spending_rate.rb
class SpendingRate < ActiveRecord::Base
  
  validates_presence_of :name
  validates_numericality_of :year
  # validates_uniqueness_of :name
  
  belongs_to :spending_category
  
  
  # callback to populate some formula fields for parent
  def after_save
    cat = SpendingCategory.find_by_id(self.spending_category_id)
    
    if ! cat.nil?
      # _sum = SpendingRate.sum(:amount, :conditions => ["spending_category_id = ?", self.spending_category_id])
      # cat.sum_amount = _sum
      #     
      # _sum = SpendingRate.sum(:rate, :conditions => ["spending_category_id = ?", self.spending_category_id])
      # cat.sum_rate = _sum
    
      cat.save! # Update the category
    end
  end
end

app/controllers/spending_rates_controller.rb
class SpendingRatesController < ApplicationController
  before_filter :require_user
  
  # GET /spending_rates
  # GET /spending_rates.xml
  def index
    @spending_rates = SpendingRate.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @spending_rates }
    end
  end

  # GET /spending_rates/1
  # GET /spending_rates/1.xml
  def show
    @spending_rate = SpendingRate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @spending_rate }
    end
  end

  # GET /spending_rates/new
  # GET /spending_rates/new.xml
  def new
    @spending_rate = SpendingRate.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @spending_rate }
    end
  end

  # GET /spending_rates/1/edit
  def edit
    @spending_rate = SpendingRate.find(params[:id])
  end

  # POST /spending_rates
  # POST /spending_rates.xml
  def create
    @spending_rate = SpendingRate.new(params[:spending_rate])

    respond_to do |format|
      if @spending_rate.save
        format.html { redirect_to(@spending_rate, :notice => 'Spending rate was successfully created.') }
        format.xml  { render :xml => @spending_rate, :status => :created, :location => @spending_rate }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @spending_rate.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /spending_rates/1
  # PUT /spending_rates/1.xml
  def update
    @spending_rate = SpendingRate.find(params[:id])

    respond_to do |format|
      if @spending_rate.update_attributes(params[:spending_rate])
        format.html { redirect_to(@spending_rate, :notice => 'Spending rate was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @spending_rate.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /spending_rates/1
  # DELETE /spending_rates/1.xml
  def destroy
    @spending_rate = SpendingRate.find(params[:id])
    @spending_rate.destroy

    respond_to do |format|
      format.html { redirect_to(spending_rates_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/spending_rates_helper.rb
module SpendingRatesHelper
end

app/views/spending_rates/_form.html.erb
<%= form_for(@spending_rate) do |f| %>
  <% if @spending_rate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spending_rate.errors.count, "error") %> prohibited this spending_rate from being saved:</h2>

      <ul>
      <% @spending_rate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>%
  </div>
  <div class="field">
    <%= f.label :spending_category_id %><br />
	<%= select("spending_rate", "spending_category_id", SpendingCategory.find(:all).collect{|c| [c.name, c.id]} ) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spending_rates/edit.html.erb
<h1>Edit Spending Rate</h1>

<%= render 'form' %>

<%= link_to 'Show', @spending_rate %> |
<%= link_to 'Back', spending_rates_path %>

app/views/spending_rates/index.html.erb
<h1>Listing Spending Rates</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Year</th>
    <th>Amount (millions USD)</th>
    <th>Category</th>
    <th></th>
    <th></th>
  </tr>

<% total = 0 %>
<% @spending_rates.each do |spending_rate| %>
  <tr>
    <td><%= link_to spending_rate.name, spending_rate %></td>
    <td><%= spending_rate.year %></td>
    <td><%= spending_rate.amount %>%</td>
    <td><%= spending_rate.spending_category.name %></td>
    <td><%= link_to 'Edit', edit_spending_rate_path(spending_rate) %></td>
    <td><%= link_to 'Destroy', spending_rate, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% total = total + spending_rate.amount %>
<% end %>
	<tr><td>Total</td><td></td><td><%= total %>%<td><td></td><td></td></tr>
</table>

<br />

<%= link_to 'New Spending rate', new_spending_rate_path %>

app/views/spending_rates/new.html.erb
<h1>Create New Spending Rate</h1>

<%= render 'form' %>

<%= link_to 'Back', spending_rates_path %>

app/views/spending_rates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @spending_rate.name %>
</p>

<p>
  <b>Description:</b>
  <%= @spending_rate.description %>
</p>

<p>
  <b>Amount (millions USD):</b>
  <%= @spending_rate.amount %>%
</p>

<p>
  <b>Spending category:</b>
  <%= @spending_rate.spending_category.name %>
</p>


<%= link_to 'Edit', edit_spending_rate_path(@spending_rate) %> |
<%= link_to 'Back', spending_rates_path %>