config/routes.rb
Taxwhere::Application.routes.draw do
  resources :filing_categories
  resources :tax_rates
  resources :spending_rates
  resources :spending_categories
  
  resource :account, :controller => "users"
  resources :users
  resource :user_session
  resources :password_resets, :only => [ :new, :create, :edit, :update ]
  resources :user_verification, :only => :show
  
  
  
  match'/tax_payers', :controller => 'welcome', :action => 'spending'
  match 'credits' => 'welcome#credits'
  match 'sources' => 'welcome#sources'
  match 'spending' => 'welcome#spending'

  root :to => "welcome#index"

end

app/models/tax_rate.rb
class TaxRate < ActiveRecord::Base
  validates_numericality_of :year
  
  belongs_to :filing_category
  
end

app/controllers/tax_rates_controller.rb
class TaxRatesController < ApplicationController
  before_filter :require_user
  
  # GET /tax_rates
  # GET /tax_rates.xml
  def index
    @tax_rates = TaxRate.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tax_rates }
    end
  end

  # GET /tax_rates/1
  # GET /tax_rates/1.xml
  def show
    @tax_rate = TaxRate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tax_rate }
    end
  end

  # GET /tax_rates/new
  # GET /tax_rates/new.xml
  def new
    @tax_rate = TaxRate.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tax_rate }
    end
  end

  # GET /tax_rates/1/edit
  def edit
    @tax_rate = TaxRate.find(params[:id])
  end

  # POST /tax_rates
  # POST /tax_rates.xml
  def create
    @tax_rate = TaxRate.new(params[:tax_rate])

    respond_to do |format|
      if @tax_rate.save
        format.html { redirect_to(@tax_rate, :notice => 'Tax rate was successfully created.') }
        format.xml  { render :xml => @tax_rate, :status => :created, :location => @tax_rate }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tax_rate.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tax_rates/1
  # PUT /tax_rates/1.xml
  def update
    @tax_rate = TaxRate.find(params[:id])

    respond_to do |format|
      if @tax_rate.update_attributes(params[:tax_rate])
        format.html { redirect_to(@tax_rate, :notice => 'Tax rate was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tax_rate.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tax_rates/1
  # DELETE /tax_rates/1.xml
  def destroy
    @tax_rate = TaxRate.find(params[:id])
    @tax_rate.destroy

    respond_to do |format|
      format.html { redirect_to(tax_rates_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/tax_rates_helper.rb
module TaxRatesHelper
end

app/views/tax_rates/_form.html.erb
<%= form_for(@tax_rate) do |f| %>
  <% if @tax_rate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tax_rate.errors.count, "error") %> prohibited this tax_rate from being saved:</h2>

      <ul>
      <% @tax_rate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :filing_category_id %><br />
	<%= select("tax_rate", "filing_category_id", FilingCategory.find(:all).collect{|c| [c.name, c.id]} ) %>
  </div>
  <div class="field">
    <%= f.label :marginal_rate %><br />
    <%= f.number_field :marginal_rate %>%
  </div>
  <div class="field">
    <%= f.label :lower_limit %><br />
    $<%= f.number_field :lower_limit %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tax_rates/edit.html.erb
<h1>Edit Tax Rates</h1>

<%= render 'form' %>

<%= link_to 'Show', @tax_rate %> |
<%= link_to 'Back', tax_rates_path %>

app/views/tax_rates/index.html.erb
<h1>List Tax Rates</h1>

<table>
  <tr>
    <th>Year</th>
    <th>Filing category</th>
    <th>Marginal rate</th>
    <th>Lower limit</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tax_rates.each do |tax_rate| %>
  <tr>
    <td><%= tax_rate.year %></td>
    <td><%= tax_rate.filing_category.name %></td>
    <td><%= tax_rate.marginal_rate %></td>
    <td><%= tax_rate.lower_limit %></td>
    <td><%= link_to 'Show', tax_rate %></td>
    <td><%= link_to 'Edit', edit_tax_rate_path(tax_rate) %></td>
    <td><%= link_to 'Destroy', tax_rate, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tax rate', new_tax_rate_path %>

app/views/tax_rates/new.html.erb
<h1>Create New Tax Rate</h1>

<%= render 'form' %>

<%= link_to 'Back', tax_rates_path %>

app/views/tax_rates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Year:</b>
  <%= @tax_rate.year %>
</p>

<p>
  <b>Filing category:</b>
  <%= @tax_rate.filing_category %>
</p>

<p>
  <b>Marginal rate:</b>
  <%= @tax_rate.marginal_rate %>
</p>

<p>
  <b>Lower limit:</b>
  <%= @tax_rate.lower_limit %>
</p>



<%= link_to 'Edit', edit_tax_rate_path(@tax_rate) %> |
<%= link_to 'Back', tax_rates_path %>