config/routes.rb
Taxwhere::Application.routes.draw do
  resources :filing_categories
  resources :tax_rates
  resources :spending_rates
  resources :spending_categories
  
  resource :account, :controller => "users"
  resources :users
  resource :user_session
  resources :password_resets, :only => [ :new, :create, :edit, :update ]
  resources :user_verification, :only => :show
  
  
  
  match'/tax_payers', :controller => 'welcome', :action => 'spending'
  match 'credits' => 'welcome#credits'
  match 'sources' => 'welcome#sources'
  match 'spending' => 'welcome#spending'

  root :to => "welcome#index"

end

app/models/filing_category.rb
class FilingCategory < ActiveRecord::Base
  
  validates_presence_of :name
  
  has_many :tax_rates, :order => 'lower_limit ASC'
end

app/controllers/filing_categories_controller.rb
class FilingCategoriesController < ApplicationController
  before_filter :require_user
  
  # GET /filing_categories
  # GET /filing_categories.xml
  def index
    @filing_categories = FilingCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @filing_categories }
    end
  end

  # GET /filing_categories/1
  # GET /filing_categories/1.xml
  def show
    @filing_category = FilingCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @filing_category }
    end
  end

  # GET /filing_categories/new
  # GET /filing_categories/new.xml
  def new
    @filing_category = FilingCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @filing_category }
    end
  end

  # GET /filing_categories/1/edit
  def edit
    @filing_category = FilingCategory.find(params[:id])
  end

  # POST /filing_categories
  # POST /filing_categories.xml
  def create
    @filing_category = FilingCategory.new(params[:filing_category])

    respond_to do |format|
      if @filing_category.save
        format.html { redirect_to(@filing_category, :notice => 'Filing category was successfully created.') }
        format.xml  { render :xml => @filing_category, :status => :created, :location => @filing_category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @filing_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /filing_categories/1
  # PUT /filing_categories/1.xml
  def update
    @filing_category = FilingCategory.find(params[:id])

    respond_to do |format|
      if @filing_category.update_attributes(params[:filing_category])
        format.html { redirect_to(@filing_category, :notice => 'Filing category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @filing_category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /filing_categories/1
  # DELETE /filing_categories/1.xml
  def destroy
    @filing_category = FilingCategory.find(params[:id])
    @filing_category.destroy

    respond_to do |format|
      format.html { redirect_to(filing_categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/filing_categories_helper.rb
module FilingCategoriesHelper
end

app/views/filing_categories/_form.html.erb
<%= form_for(@filing_category) do |f| %>
  <% if @filing_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@filing_category.errors.count, "error") %> prohibited this filing_category from being saved:</h2>

      <ul>
      <% @filing_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :standard_deduction %><br />
    $<%= f.number_field :standard_deduction %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/filing_categories/edit.html.erb
<h1>Editing filing_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @filing_category %> |
<%= link_to 'Back', filing_categories_path %>

app/views/filing_categories/index.html.erb
<h1>Listing filing_categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Std Deduction</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @filing_categories.each do |filing_category| %>
  <tr>
    <td><%= filing_category.name %></td>
    <td><%= filing_category.description %></td>
    <td>$<%= filing_category.standard_deduction %></td>
    <td><%= link_to 'Show', filing_category %></td>
    <td><%= link_to 'Edit', edit_filing_category_path(filing_category) %></td>
    <td><%= link_to 'Destroy', filing_category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Filing category', new_filing_category_path %>

app/views/filing_categories/new.html.erb
<h1>New filing_category</h1>

<%= render 'form' %>

<%= link_to 'Back', filing_categories_path %>

app/views/filing_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @filing_category.name %>
</p>

<p>
  <b>Description:</b>
  <%= @filing_category.description %>
</p>

<p>
  <b>Standard Deduction:</b>
  $<%= @filing_category.standard_deduction %>
</p>

<p>
  <b>Has <%= @filing_category.tax_rates.count%> tax rates</b><br />
	<% if @filing_category.tax_rates.count > 0 %>
	<table>
		<tr><th>Marginal Rate</th><th>Lower Limit</th></tr>
		<% for tax_rate in @filing_category.tax_rates%>
		<tr>
			<td><%= tax_rate.marginal_rate%>%</td><td>$<%= tax_rate.lower_limit%></td>
		</tr>
		<% end %>
	</table>
	<% end %>
</p>

<%= link_to 'Edit', edit_filing_category_path(@filing_category) %> |
<%= link_to 'Back', filing_categories_path %>